# Generated by Django 4.2.28 on 2026-03-03 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/%Y/%m/%d/')),
                ('predicted_label', models.CharField(choices=[('Ripe', 'Ripe'), ('Unripe', 'Unripe'), ('Overripe', 'Overripe'), ('Rotten', 'Rotten')], max_length=20)),
                ('confidence', models.FloatField(help_text='Confidence score 0-1')),
                ('grade', models.CharField(choices=[('Grade A', 'Grade A'), ('Grade B', 'Grade B'), ('Grade C', 'Grade C'), ('Reject', 'Reject')], max_length=10)),
                ('detection_method', models.CharField(choices=[('upload', 'Single Upload'), ('batch', 'Batch Upload'), ('live', 'Live Detection'), ('capture', 'Manual Capture')], max_length=10)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['predicted_label'], name='detection_d_predict_2bfd00_idx'), models.Index(fields=['grade'], name='detection_d_grade_eafae0_idx'), models.Index(fields=['detection_method'], name='detection_d_detecti_a4a646_idx')],
            },
        ),
    ]
