# Generated by Django 4.2.28 on 2026-03-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionrecord',
            name='fruit_type',
            field=models.CharField(choices=[('apple', 'Apple'), ('mango', 'Mango')], default='apple', max_length=10),
        ),
        migrations.AddIndex(
            model_name='detectionrecord',
            index=models.Index(fields=['fruit_type'], name='detection_d_fruit_t_1e0a64_idx'),
        ),
    ]
