# Generated by Django 4.2.28 on 2026-03-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_detectionrecord_fruit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrecord',
            name='predicted_label',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Bruised', 'Bruised'), ('Rot', 'Rot'), ('Rotten', 'Rotten'), ('Scab', 'Scab'), ('Black Spot', 'Black Spot')], max_length=20),
        ),
    ]
