# Generated by Django 4.2.29 on 2026-03-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_alter_detectionrecord_predicted_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrecord',
            name='fruit_type',
            field=models.CharField(choices=[('apple', 'Apple'), ('orange', 'Orange'), ('mango', 'Mango'), ('grapes', 'Grapes'), ('banana', 'Banana')], default='apple', max_length=10),
        ),
        migrations.AlterField(
            model_name='detectionrecord',
            name='predicted_label',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Bruised', 'Bruised'), ('Rot', 'Rot'), ('Rotten', 'Rotten'), ('Scab', 'Scab'), ('Black Spot', 'Black Spot'), ('Overripe', 'Overripe'), ('Unripe', 'Unripe'), ('Sun Burn', 'Sun Burn'), ('Mold', 'Mold')], max_length=20),
        ),
    ]
