# Generated by Django 4.2.29 on 2026-03-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_detectionrecord_fruit_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionrecord',
            name='predicted_label',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Rotten', 'Rotten')], max_length=20),
        ),
    ]
